### ISSUE TITLE
Registro de "issues"

### ISSUE THREAD

**Issue by norman-ipn** [shikimx/TT2019A104R#1]
Hola,
vamos a usar este medio para ir revisando los detalles que tengas con \LaTex.
Genera un issue y etiquétame, para poder atenderlo.

**Comment by norman-ipn** [comment]
Cada capítulo estará en un archivo .tex separado para poder compilar por partes.
Ya subí el ejemplo. También agregé el Makefile de ejemplo.

**Comment by norman-ipn** [comment]
Cierra este issue en cuanto puedas. @shikimx

**Comment by shikimx** [comment]
Archivos separados
