### ISSUE TITLE
Al compilar no se agregan citas ni referencias

### ISSUE THREAD

**Issue by shikimx** [shikimx/TT2019A104R#3]
En el nuevo PDF del nuevo commit no hay ninguno de los datos anteriores, a pesar de que en veriosnes anteriores no se tuvo este problema. @norman-ipn 
[reporte.pdf](https://github.com/shikimx/TT2019A104R/files/5098397/reporte.pdf)

**Comment by norman-ipn** [comment]
los signos de interrogación indican que requiere doble compilación, lo reviso y lo corrigo.

**Comment by shikimx** [comment]
Se ha compilado multibles veces, especificamente en el orden de PDFLatex+Bibtex+PDFLatex+PDFLatex.

**Comment by norman-ipn** [comment]
Listo, ya lo probé y agregé las dependencias al Makefile. Ya se genera el archivo .pdf con las referencias.
