### ISSUE TITLE
Error al compilar.

### ISSUE THREAD

**Issue by shikimx** [shikimx/TT2019A104R#5]
He intentado compilar mediante MAKE y Texmaker y obtengo 2 errores diferentes.

 Make:
<pre>Package caption Warning: The option `hypcap=true&apos; will be ignored for this
(caption)                particular \caption on input line 51.
See the caption package documentation for explanation.

[11 &lt;./source/images/image22.png&gt;]
! Too many }&apos;s.
\@endfloatbox ...pagefalse \outer@nobreak \egroup 
                                                  \color@endbox 
l.53 \end{figure}
      </pre>

TexMaker:
! TeX capacity exceeded, sorry [main memory size=5000000].\@x@protect #1\fi #2#3->\fi \protect#1 ...ara el estudio del sistema en cuestión.\\

No he podido encontrar un { } extra dentro del  C2_MC.tex
 Y en TexMaker me da un error diferente. :-1: 

Llevo una buena parte del dia intentando resolverlo.

**Comment by norman-ipn** [comment]
No vuelvas a perder tiempo intentando compilar, dedicata a escribir el texto. Concéntrate en las ideas, en las palabras en los conceptos, yo te ayudo con la sintáxis de LaTeX. A partir de ahora sólo revisa cosas que tengan que ver con el contenido. Repito, tiene prioridad el contenido, el texto, el código fuente de la aplicación, los diagramas, la metodología, los modelos 3D, etcétera. Por favor, para poder terminar en tiempo las modificaciones debes aprovechar las tres horas que tienes para atender cosas de fondo, cosas del TT.

**Comment by norman-ipn** [comment]
Yo cierro este issue cuando ya compile.

**Comment by norman-ipn** [comment]
Listo, 
Si vas copiar y pegar código asegúrate de que este completo. Quedaron colgando unos \end sin sus correspondientes \begin.
También había problemas con el nombre de una referencia.
