### ISSUE TITLE
Longtable en C3_SP

### ISSUE THREAD

**Issue by shikimx** [shikimx/TT2019A104R#7]
No se puede compilar debido a la longtable que se integró.
No he encontrado algún error de sintáxis de la tabla.

**Comment by norman-ipn** [comment]
Yo reviso la compilación, tu concéntrate en el contenido.

**Comment by shikimx** [comment]
Estoy en eso.

**Comment by norman-ipn** [comment]
listo, ya compila. Has tablas sencillas, no importa el color, importa el contenido.
